const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_CATEGORIES = 'SET_CATEGORIES';
const CHANGE_IS_LOADER_PRODUCT = 'CHANGE_IS_LOADER_PRODUCT';
const CHANGE_IS_LOADER_CATEGORIES = 'CHANGE_IS_LOADER_CATEGORIES';

export {SET_CATEGORIES, SET_PRODUCTS, CHANGE_IS_LOADER_PRODUCT, CHANGE_IS_LOADER_CATEGORIES};